title: LineCruncher
logo: /assets/img/updated-linecruncher-june-2018.png
description: The blog for all things NHL DFS & Edmonton Oilers
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
